import React from 'react'
import { useState, useCallback, useEffect } from 'react'

import ReactDOM from 'react-dom/client'
import { LhasaComponent } from './Lhasa.tsx'
import './index.scss'
// import { Window } from './index';
import { FormControlLabel, Switch, Grid } from '@mui/material'

// // Type definitions for TS linter, auto-generated by Embind
// import { MainModule } from './types'





export function App() {
  const [showLhasa, setShowLhasa] = useState(true);
  const [darkMode, setDarkMode] = useState(false);
  const [showFooter, setShowFooter] = useState(true);
  const [showTopPanel, setShowTopPanel] = useState(true);
  const [isLhasaAttached, setLhasaAttached] = useState(window.LhasaModule !== undefined);

  const handleLhasaAttached = useCallback(() => {
      if (window.LhasaModule !== undefined) {
          setLhasaAttached(true);
      } else {
          console.warn("Lhasa module not available... Cannot start Lhasa.")
      }
  }, []);

  useEffect(() => {
      document.addEventListener('lhasaModuleAttached', handleLhasaAttached);
      return () => {
          document.removeEventListener('lhasaModuleAttached', handleLhasaAttached)
      };
  }, [handleLhasaAttached]);


  let MaybeLhasaComponent = isLhasaAttached ?
  <LhasaComponent 
    Lhasa={window.LhasaModule} 
    show_top_panel={showTopPanel}
    show_footer={showFooter}
    icons_path_prefix='icons'
    smiles_callback={(internal_id, id_from_prop, smiles) => console.log("ID=", internal_id," SMILES=", smiles, "Id-From-Prop", id_from_prop)}
    // Works when using `npx vite server --port 5174`
    // Inside `vite.config.js` there is a proxy setup to redirect this to an actual bansu instance.
    // CORS stuff is broken for localhost connections, it seems.
    // bansu_endpoint='http://localhost:5174'

    bansu_endpoint='https://quicillith.pl'
    data_path_prefix=''
    dark_mode={darkMode}
  /> : <div>
    Lhasa module not loaded yet
  </div>;

  return (
    <>
    <Grid container columns={2} sx={{ maxWidth: 400 }}>
      <Grid size={1}>
        <FormControlLabel
          control={<Switch checked={showLhasa} onChange={(event) => setShowLhasa(event.target.checked)} />}
          label={"Show Lhasa"}
        />
      </Grid>
      <Grid size={1}>
        <FormControlLabel
          control={<Switch checked={darkMode} onChange={(event) => setDarkMode(event.target.checked)} />}
          label={"Dark Mode"}
        />
      </Grid>
      <Grid size={1}>
        <FormControlLabel
          control={<Switch checked={showFooter} onChange={(event) => setShowFooter(event.target.checked)} />}
          label={"Show Footer"}
        />
      </Grid>
      <Grid size={1}>
        <FormControlLabel
          control={<Switch checked={showTopPanel} onChange={(event) => setShowTopPanel(event.target.checked)} />}
          label={"Show Top Panel"}
        />
      </Grid>
    </Grid>
     {showLhasa ? MaybeLhasaComponent : null}
    </>
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)