import React from 'react'
import { useState} from 'react'

import ReactDOM from 'react-dom/client'
import { LhasaComponent } from './Lhasa.tsx'
import './index.scss'
import Module from '/lhasa.js?url'
// Type definitions for TS linter, auto-generated by Embind
import { MainModule } from './lhasa'
import { FormControl, FormControlLabel, Switch } from '@mui/material'

const lhasa_module : MainModule = await Module();



export function App() {
  const [showLhasa, setShowLhasa] = useState(true);

  return (
    <>
    <FormControl>
      <FormControlLabel
        control={<Switch checked={showLhasa} onChange={(event) => setShowLhasa(event.target.checked)} />}
        label={"Show Lhasa"} 
      />
    </FormControl>
     {showLhasa && 
      <LhasaComponent 
        Lhasa={lhasa_module} 
        show_top_panel={true}
        // show_footer={true}
        icons_path_prefix='/icons'
        smiles_callback={(internal_id, id_from_prop, smiles) => console.log("ID=", internal_id," SMILES=", smiles, "Id-From-Prop", id_from_prop)}
        bansu_endpoint={{ hostname: 'localhost', port:8080}}
      />}
    </>
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)