import React from 'react'
import { useState, useCallback, useEffect, useRef } from 'react'

import ReactDOM from 'react-dom/client'
import { LhasaComponent } from './Lhasa.tsx'
import './index.scss'
import './main.scss'
// import { Window } from './index';
import { FormControlLabel, Switch, Grid, Collapse, TextField, Checkbox } from '@mui/material'

// // Type definitions for TS linter, auto-generated by Embind
// import { MainModule } from './types'

function PixelConstraintInput(props: {label: string, value: number, onChange: (v: number) => void, disabled: boolean}) {
  return <TextField
    label={props.label}
    type="number"
    size="small"
    value={props.value}
    onChange={(e) => props.onChange(Number(e.target.value))}
    disabled={props.disabled}
    slotProps={{ htmlInput: { min: 0 } }}
  />;
}





export function App() {
  const [showLhasa, setShowLhasa] = useState(true);
  const [darkMode, setDarkMode] = useState(false);
  const [showFooter, setShowFooter] = useState(true);
  const [showTopPanel, setShowTopPanel] = useState(true);
  const [showSizingConstraints, setShowSizingConstraints] = useState(false);

  const [widthConstraintEnabled, setWidthConstraintEnabled] = useState(false);
  const [widthConstraint, setWidthConstraint] = useState(800);
  const [heightConstraintEnabled, setHeightConstraintEnabled] = useState(false);
  const [heightConstraint, setHeightConstraint] = useState(800);

  const [maxWidthConstraintEnabled, setMaxWidthConstraintEnabled] = useState(false);
  const [maxWidthConstraint, setMaxWidthConstraint] = useState(1600);
  const [maxHeightConstraintEnabled, setMaxHeightConstraintEnabled] = useState(false);
  const [maxHeightConstraint, setMaxHeightConstraint] = useState(1024);

  const [isLhasaAttached, setLhasaAttached] = useState(window.LhasaModule !== undefined);
  const dragging = useRef(false);
  const dragStart = useRef({x: 0, y: 0, w: 0, h: 0});

  const onResizeHandlePointerDown = useCallback((e: React.PointerEvent) => {
    dragging.current = true;
    dragStart.current = {x: e.clientX, y: e.clientY, w: widthConstraint, h: heightConstraint};
    setWidthConstraintEnabled(true);
    setHeightConstraintEnabled(true);
    (e.target as HTMLElement).setPointerCapture(e.pointerId);
  }, [widthConstraint, heightConstraint]);

  const onResizeHandlePointerMove = useCallback((e: React.PointerEvent) => {
    if (!dragging.current) return;
    const {x, y, w, h} = dragStart.current;
    setWidthConstraint(Math.max(0, w + e.clientX - x));
    setHeightConstraint(Math.max(0, h + e.clientY - y));
  }, []);

  const onResizeHandlePointerUp = useCallback(() => {
    dragging.current = false;
  }, []);

  const handleLhasaAttached = useCallback(() => {
      if (window.LhasaModule !== undefined) {
          setLhasaAttached(true);
      } else {
          console.warn("Lhasa module not available... Cannot start Lhasa.")
      }
  }, []);

  useEffect(() => {
      document.addEventListener('lhasaModuleAttached', handleLhasaAttached);
      return () => {
          document.removeEventListener('lhasaModuleAttached', handleLhasaAttached)
      };
  }, [handleLhasaAttached]);


  let MaybeLhasaComponent = isLhasaAttached ?
  <LhasaComponent 
    Lhasa={window.LhasaModule} 
    show_top_panel={showTopPanel}
    show_footer={showFooter}
    icons_path_prefix='icons'
    smiles_callback={(internal_id, id_from_prop, smiles) => console.log("ID=", internal_id," SMILES=", smiles, "Id-From-Prop", id_from_prop)}
    // Works when using `npx vite server --port 5174`
    // Inside `vite.config.js` there is a proxy setup to redirect this to an actual bansu instance.
    // CORS stuff is broken for localhost connections, it seems.
    // bansu_endpoint='http://localhost:5174'

    bansu_endpoint='https://quicillith.pl'
    data_path_prefix=''
    dark_mode={darkMode}
    width={widthConstraintEnabled ? widthConstraint : null}
    height={heightConstraintEnabled ? heightConstraint : null}
    max_width={maxWidthConstraintEnabled ? maxWidthConstraint : null}
    max_height={maxHeightConstraintEnabled ? maxHeightConstraint : null}
  /> : <div>
    Lhasa module not loaded yet
  </div>;

  return (
    <>
    <div className="lhasa_editor" style={{ backgroundColor: "transparent"}}>
      <Grid container columns={2}>
        <Grid size={1}>
          <FormControlLabel
            control={<Switch checked={showLhasa} onChange={(event) => setShowLhasa(event.target.checked)} />}
            label={"Show Lhasa"}
          />
        </Grid>
        <Grid size={1}>
          <FormControlLabel
            control={<Switch checked={darkMode} onChange={(event) => setDarkMode(event.target.checked)} />}
            label={"Dark Mode"}
          />
        </Grid>
        <Grid size={1}>
          <FormControlLabel
            control={<Switch checked={showFooter} onChange={(event) => setShowFooter(event.target.checked)} />}
            label={"Show Footer"}
          />
        </Grid>
        <Grid size={1}>
          <FormControlLabel
            control={<Switch checked={showTopPanel} onChange={(event) => setShowTopPanel(event.target.checked)} />}
            label={"Show Top Panel"}
          />
        </Grid>
        <Grid size={2}>
          <FormControlLabel
            control={<Switch checked={showSizingConstraints} onChange={(event) => setShowSizingConstraints(event.target.checked)} />}
            label={"Sizing Constraints"}
          />
        </Grid>
      </Grid>
      <Collapse in={showSizingConstraints}>
        <div className="vertical_panel" style={{ maxWidth: 400, paddingBottom: 10}}>
          <b>Fixed Size</b>
          <Grid container columns={2}>
            <Grid size={1}>
              <div className="horizontal_container_centered">
                <Checkbox checked={widthConstraintEnabled} onChange={(e) => setWidthConstraintEnabled(e.target.checked)} size="small" />
                <PixelConstraintInput label="width" value={widthConstraint} onChange={setWidthConstraint} disabled={!widthConstraintEnabled} />
              </div>
            </Grid>
            <Grid size={1}>
              <div className="horizontal_container_centered">
                <Checkbox checked={heightConstraintEnabled} onChange={(e) => setHeightConstraintEnabled(e.target.checked)} size="small" />
                <PixelConstraintInput label="height" value={heightConstraint} onChange={setHeightConstraint} disabled={!heightConstraintEnabled} />
              </div>
            </Grid>
          </Grid>
          <b>Max Size Limits</b>
          <Grid container columns={2}>
            <Grid size={1}>
              <div className="horizontal_container_centered">
                <Checkbox checked={maxWidthConstraintEnabled} onChange={(e) => setMaxWidthConstraintEnabled(e.target.checked)} size="small" />
                <PixelConstraintInput label="max_width" value={maxWidthConstraint} onChange={setMaxWidthConstraint} disabled={!maxWidthConstraintEnabled} />
              </div>
            </Grid>
            <Grid size={1}>
              <div className="horizontal_container_centered">
                <Checkbox checked={maxHeightConstraintEnabled} onChange={(e) => setMaxHeightConstraintEnabled(e.target.checked)} size="small" />
                <PixelConstraintInput label="max_height" value={maxHeightConstraint} onChange={setMaxHeightConstraint} disabled={!maxHeightConstraintEnabled} />
              </div>
            </Grid>
          </Grid>
        </div>
      </Collapse>
    </div>
     {showLhasa ? <div className={darkMode ? 'lhasa_dark_mode' : undefined} style={{position: 'relative', width: 'fit-content'}}>
       {MaybeLhasaComponent}
       {showSizingConstraints && <div
         className="lhasa_resize_handle"
         onPointerDown={onResizeHandlePointerDown}
         onPointerMove={onResizeHandlePointerMove}
         onPointerUp={onResizeHandlePointerUp}
       />}
     </div> : null}
    </>
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)